// @ts-nocheck

export const TOPIC_NOUN = [
  'chuối',
  'nô lệ',
  'con người',
  'yêu tinh',
  'orc',
  'neko',
  'người hổ',
  'tiên nữ',
  'thiên thần',
  'người rồng',
  'người thằn lằn',
  'người nước ngoài',
  'nhiệm vụ',
  'phiêu lưu',
  'kiếm',
  'rìu',
  'cung',
  'rồng',
  'nấu ăn',
  'rượu mật ong',
  'trò chơi',
  'thơ ca',
  'thể thao',
  'tập thể dục',
  'cơ bắp',
  'tình dục',
  'quan hệ qua đường hậu môn',
  'quan hệ bằng miệng',
  'quan hệ qua đường âm đạo',
  'nô lệ ngựa',
  'nô lệ thú cưng',
  'âm nhạc',
  'hội họa',
  'sức khỏe',
  'lịch sử',
  'toán học',
  'động vật',
  'thực vật',
  'dương vật',
  'tinh hoàn',
  'âm đạo',
  'hậu môn',
  'ngực',
  'các mối quan hệ',
  'tôn giáo',
  'chính trị',
  'đời sống tình cảm',
  'tội phạm',
  'sự nghiệp buôn bán nô lệ',
  'hiệp sĩ',
  'nông dân',
  'sữa',
  'giao thương',
  'phép thuật',
  'thung lũng phía bắc',
  'biển phía nam',
  'rừng phía tây',
  'sa mạc phía đông',
  'sâu sắc',
  'gái tóc vàng hoe',
  'nô lệ bị hủy hoại tâm trí',
  'nặn xác thịt',
  'sự tha hóa',
  'sự thanh tẩy',
  'nhiệm vụ',
  'tiền bạc',
  'danh tiếng',
  'thời trang',
  'áo giáp',
  'trói buộc',
  'nô lệ phục tùng',
  'chủ nô thống trị',
  'công nghệ',
  'lãng mạn',
  'tình yêu',
  'thú cưng',
  'giáo dục',
  'lính đánh thuê',
  'cướp biển',
  'gái điếm',
  'binh lính',
  'kẻ cướp',
  'quỷ dữ',
  'người chữa trị',
  'chữa lành',
  'chế tạo',
  'thuốc',
  'tổn thương',
  'trang bị',
  'công việc',
  'chiến đấu',
  'sinh tồn',
  'lén lút',
  'buôn bán nô lệ',
  'kiến thức',
  'gia đình',
  'núm vú',
  'đôi cánh',
  'đuôi',
  'nô lệ chữa trị dâm đãng',
  'tình bạn',
  'sự kình địch',
  'những sai lầm',
  'những chiến thắng',
  'ngày mai',
  'hôm qua',
  'tháng sau',
  'tháng trước',
  'tuần sau',
  'tuần trước',
  'thôi miên',
  'nô lệ gia đình',
  'những kẻ ẻo lả',
  'chủ nghĩa phô dâm',
  'sự kìm nén',
  'nhập vai',
  'nghiện tình dục',
  'ma',
  'thiên nhiên',
  'ngủ',
  'chơi chữ',
  'nhà',
  'vệ sinh',
  'khoa học',
  'xúc tu',
  'những ân huệ',
  'những thứ ghê tởm từ thế giới khác',
  'Thành phố Cảng Neko',
  'hậu cung',
  'lương thấp',
  'mộng tinh',
  "bữa tối",
  "khó tiêu",
  "Màn Sương",
  "cái lạnh",
  "cái nóng",
  "tình cũ",
  "bảo vệ khi quan hệ",
  "nấm",
  "bàn chân",
  "tạ đòn",
  "sự cọ xát",
  "mèo",
  "chó",
  "triết học",
  "trà",
  "tin đồn",
  "mông to",
  "mông lép",
  "bánh ngọt",
  "sinh nhật",
  "vết thương",
  "khiêu vũ",
  "tù nhân",
  "mạng lưới quan hệ",
  "tình một đêm",
  "răng nanh orc",
  "tai elf",
  "lông tơ",
  "các thế giới khác",
  "dương vật giả",
  "trái cây tươi",
  "kiếp sau",
  "bình minh",
  "hoàng hôn",
  "rượu mạnh",
  'quan hệ bằng đuôi',
  'tư thế truyền giáo',
  'nhà thổ',
  'phép thuật lửa',
  'phép thuật nước',
  'phép thuật đất',
  'phép thuật gió',
  'hắc thuật',
  'quang thuật',
  'phô mai cũ',
  'quái vật xúc tu',
  'chứng mất ngủ',
  'nô lệ ngoan cố',
  'lính đánh thuê',
  'giếng ước',
  'xác sống',
  'bịt mắt',
  'bánh kem',
  'trinh tiết',
  'quái vật',
  'rau củ',
  'xác chết',
]

export const BANTER_TOPIC = [
  'bạn',
  'chủng tộc của bạn',
  'giới tính của bạn',
  'tính cách của bạn',
  'kỹ năng của bạn',
  'sự nghiệp của bạn',
  'công ty',
  'các sự kiện gần đây',
  'nô lệ',
  'nô lệ mới',
  'cuộc sống quá khứ của họ',
  'con người',
  'yêu tinh',
  'Vương quốc Tor',
  'Thành phố Lucgate',
  'orc',
  'neko',
  'người hổ',
  'tiên nữ',
  'thiên thần',
  'người rồng',
  'người thằn lằn',
  'người nước ngoài',
  'nhiệm vụ',
  'nhiệm vụ gần đây',
  'nhiệm vụ trong quá khứ',
  'phiêu lưu',
  'kiếm',
  'rồng',
  'văn hóa',
  'nấu ăn',
  'sở thích',
  'văn học',
  'nghệ thuật',
  'giải trí',
  'trò chơi',
  'thơ ca',
  'thể thao',
  'tập thể dục',
  'cơ bắp',
  'tình dục',
  'quan hệ qua đường hậu môn',
  'quan hệ bằng miệng',
  'quan hệ qua đường âm đạo',
  'nô lệ ngựa',
  'nô lệ thú cưng',
  'âm nhạc',
  'hội họa',
  'sức khỏe',
  'lịch sử',
  'toán học',
  'động vật',
  'thực vật',
  'dương vật',
  'tinh hoàn',
  'âm đạo',
  'hậu môn',
  'ngực',
  'các mối quan hệ',
  'tôn giáo',
  'chính trị',
  'đời sống tình cảm',
  'tội phạm',
  'sự nghiệp buôn bán nô lệ',
  'hiệp sĩ',
  'nông dân',
  'sữa',
  'giao thương',
  'phép thuật',
  'thung lũng phía bắc',
  'biển phía nam',
  'rừng phía tây',
  'sa mạc phía đông',
  'gái tóc vàng hoe',
  'nô lệ bị hủy hoại tâm trí',
  'nặn xác thịt',
  'sự tha hóa',
  'sự thanh tẩy',
  'nhiệm vụ',
  'sự lãnh đạo của bạn',
  'bạn bè của họ',
  'đối thủ của họ',
  'tương lai',
  'quá khứ',
  'thế giới',
  'giấc mơ của họ',
  'tiền bạc',
  'danh tiếng',
  'du lịch',
  'thời tiết',
  'thức ăn',
  'thời trang',
  'áo giáp',
  'trói buộc',
  'khỏa thân',
  'nô lệ phục tùng',
  'chủ nô thống trị',
  'công nghệ',
  'lãng mạn',
  'tình yêu',
  'thú cưng',
  'giáo dục',
  'lính đánh thuê',
  'cướp biển',
  'gái điếm',
  'binh lính',
  'kẻ cướp',
  'quỷ dữ',
  'người chữa trị',
  'chữa lành',
  'chế tạo',
  'thuốc',
  'tổn thương',
  'trang bị',
  'lý lịch của họ',
  'giới tính của họ',
  'chủng tộc của họ',
  'tính cách của họ',
  'công việc',
  'chiến đấu',
  'sinh tồn',
  'lén lút',
  'buôn bán nô lệ',
  'kiến thức',
  'đời sống xã hội',
  'đời sống tình dục',
  'gia đình',
  'núm vú',
  'đôi cánh',
  'đuôi',
  'nô lệ chữa trị dâm đãng',
  'tình bạn',
  'sự kình địch',
  'những sai lầm',
  'những chiến thắng',
  'pháo đài',
  'ngày mai',
  'hôm qua',
  'tháng sau',
  'tháng trước',
  'tuần sau',
  'tuần trước',
  'thôi miên',
  'huấn luyện nô lệ',
  'nô lệ gia đình',
  'những kẻ ẻo lả',
  'chủ nghĩa phô dâm',
  'sự kìm nén',
  'nhập vai',
  'nghiện tình dục',
  'ma',
  'thiên nhiên',
  'ngủ',
  'chơi chữ',
  'nhà',
  'vệ sinh',
  'khoa học',
  'xúc tu',
  'những ân huệ',
  'những thứ ghê tởm từ thế giới khác',
  'Thành phố Cảng Neko',
  'hậu cung',
  'lương thấp',
  'mộng tinh',
  "bữa tối",
  "khó tiêu",
  "Màn Sương",
  "cái lạnh",
  "cái nóng",
  "tình cũ",
  "bảo vệ khi quan hệ",
  "vết phát ban tồi tệ",
  "nấm",
  "bàn chân",
  "tập thể dục",
  "tiết kiệm",
  "mua quần áo mới",
  "sự cọ xát",
  "thứ đó",
  "tẩy vết bẩn khỏi quần áo",
  "bài hát yêu thích",
  "mèo thông thường",
  "bảo trì vũ khí",
  "quần lót thủng",
  "đeo mặt nạ khi đột kích",
  "đạo đức của việc buôn bán nô lệ",
  "triết học",
  "trà",
  "tin đồn",
  "mùi đó",
  "người cao",
  "người lùn",
  "mông to",
  "mông lép",
  "bánh ngọt",
  "sinh nhật",
  "vết thương",
  "sẹo",
  "bạn thời thơ ấu",
  "chữ viết tay hoàn hảo",
  "chữ viết tay kinh khủng",
  "chủ nô mới",
  "ý nghĩa tên của bạn",
  "nhà lãnh đạo vinh quang của chúng ta",
  "khiêu vũ",
  "tù nhân",
  "nô lệ yêu thích",
  "mạng lưới quan hệ",
  "tình một đêm",
  "bầu trời đêm",
  "răng nanh orc",
  "tai elf",
  "lông tơ",
  "các thế giới khác",
  "dương vật giả",
  "trái cây tươi",
  "kiếp sau",
  "bình minh",
  "hoàng hôn",
  "cuộc sống về đêm tại trại",
  "thảm dệt tay của yêu tinh",
  "gia vị rồng từ Vùng đất phía Nam",
  "rượu của orc",
  "xà phòng người sói",
  "rượu sữa mật ong neko",
  "áo khoác lông thú phương Bắc",
  "kẻ móc túi ở Lucgate",
  "dao răng pha lê phương Đông",
  "món cà tím của Vương quốc Tor",
  "rắn biển hút thủy thủ",
  "ẩm thực Màn Sương",
  'quan hệ bằng đuôi',
  'tư thế truyền giáo',
  'nhà thổ',
  'phép thuật lửa',
  'phép thuật nước',
  'phép thuật đất',
  'phép thuật gió',
  'hắc thuật',
  'quang thuật',
  'phô mai cũ',
  'quái vật xúc tu',
  'cơn say tồi tệ',
  'chứng mất ngủ',
  'nô lệ ngoan cố',
  'danh hiệu của bạn',
  "danh tiếng công ty của bạn",
  'nhiệm vụ mới nhất',
  'lính đánh thuê',
  'giếng ước',
  'xác sống',
  'bịt mắt',
  'bánh kem',
  'trinh tiết',
  'quái vật',
  'rau củ',
  'xác chết',
  'chuối',
]
