// @ts-nocheck

export const BANTER_VERB_SLAVER_FRIEND = [
  {
    verbs: [
      `nói chuyện với b|rep`,
      `tán gẫu với b|rep`,
      `buôn chuyện với b|rep`,
      `thảo luận với b|rep`,
      `trò chuyện với b|rep`,
      `luyện tập với b|rep`,
      `đùa giỡn với b|rep`,
      `tán tỉnh b|rep`,
      `âm mưu với b|rep`,
      `lên kế hoạch với b|rep`,
      `làm vui lòng b|rep`,
      `đi chơi với b|rep, nói chuyện`,
      `tán tỉnh b|rep`,
      `dành thời gian với b|rep, nói chuyện`,
      `kết bạn với b|rep trong khi thảo luận`,
      `khuyên bảo b|rep`,
      `xin lời khuyên của b|rep`,
      `giúp đỡ b|rep`,
      `thư giãn với b|rep trong khi nói chuyện`,
      `nghỉ ngơi với b|rep trong khi nói chuyện`,
      `ủng hộ b|rep trong khi thảo luận`,
      `đùa giỡn với b|rep trong khi nói chuyện`,
      `thú nhận với b|rep`,
      `đánh bạc với b|rep trong khi đùa giỡn`,
      `đồng ý với những gì b|rep nghĩ`,
      `ủng hộ những gì b|rep nghĩ`,
      `đồng thuận với những gì b|rep nghĩ`,
      `tìm hiểu ý kiến của b|rep`,
      `trao đổi ý kiến với b|rep`,
      `trao đổi suy nghĩ với b|rep`,
      `cùng nhau chỉ trích một thứ gì đó với b|rep trong khi nói chuyện`,
      `lý thuyết hóa với b|rep`,
      `thích thú nói chuyện với b|rep`,
      `làm công việc bảo trì với b|rep trong khi nói chuyện`,
      `ăn cùng b|rep trong khi tán gẫu`,
      `uống cùng b|rep trong khi nói chuyện`,
      `tắm cùng b|rep trong khi nói chuyện`,
      `chào hỏi b|rep`,
      `kể một câu chuyện cười cho b|rep`,
      `hiểu được suy nghĩ của b|rep là gì`,
      `chia sẻ một bí mật với b|rep`,
      `ngủ chung giường với b|rep trong khi nói chuyện`,
      `chào b|rep`,
      `ôm b|rep`,
      `chia sẻ một câu chuyện cho b|rep`,
      `chia sẻ một cuốn sách cho b|rep`,
      `hỏi b|rep`,
      `khen ngợi b|rep`,
      `công nhận kiến thức của b|rep`,
      `hỏi kiến thức của b|rep`,
      `nói về quá khứ của b|rep`,
      `an ủi b|rep`,
      `làm b|rep vui lên`,
      `khen ngợi b|rep`,
      `xin lỗi b|rep`,
      `khen ngợi b|rep`,
      `bày tỏ sự ngưỡng mộ đối với b|rep`,
      `nịnh hót b|rep`,
      `chia buồn với b|rep`,
      `lừa b|rep nghĩ rằng`,
      `thua b|rep trong trò ném đá trên mặt nước, trong khi lơ đãng nói chuyện`,
      `chỉ cho b|rep các hình dạng trên mây, trong khi trầm ngâm`,
      `lơ đãng mài dao trong khi nói chuyện với b|rep`,
      `ngồi quanh trại với b|rep, tra dầu vào lưỡi dao trong khi thảo luận`,
      `đánh bóng một bộ áo giáp đến sáng như gương, trong khi b|rep lan man`,
      `vá lại quần áo rách với b|rep trong khi tán gẫu`,
      `phơi một số đồ giặt ướt với b|rep trong khi nói chuyện`,
      `chặt củi với b|rep trong khi thảo luận`,
      `kỳ lưng cho b|rep bằng khăn tắm trong khi nói chuyện`,
      `ăn bữa ăn của b|rep, dừng lại giữa các miếng ăn để thảo luận`,
      `cùng b|rep nhai những chiếc bánh quy cũ, tán gẫu`,
      `ăn nửa bánh phô mai Thung lũng phương Bắc, vì một vụ cá cược với b|rep`,
      `gặm thịt khô dai như da của người sói làm, thỉnh thoảng dừng lại để nói chuyện với b|rep`,
      `chia sẻ một vài quả yêu tinh với b|rep trong khi trò chuyện`,
      `dùng chung một bữa cơm paella neko với b|rep và tán gẫu`,
      `nhìn b|rep ăn hết một chiếc bánh mì dẹt phương Đông với cơm, trong khi nói chuyện`,
      `ngấu nghiến một xiên kebab kiểu orc mà b|rep làm, trong khi b|rep ba hoa`,
      `cùng b|rep húp một bát mì "râu rồng", nói chuyện`,
      `tự hỏi liệu con cá sống mà b|rep bắt có đủ ngon để làm sushi không, trong khi tán gẫu`,
      `đưa cho b|rep một ít bia địa phương nhạt, trong khi tán gẫu`,
      `uống một ly rượu khoai tây của người sói trong khi lan man với b|rep`,
      `mở một thùng bia đen Thung lũng phương Bắc với b|rep để nói chuyện`,
      `cùng b|rep uống cạn một chai rượu mật ong neko, trong khi thảo luận`,
      `khóc bên ly rượu yêu tinh, thú nhận với b|rep`,
      `nhìn chằm chằm vào một ly cocktail đầy trái cây từ Lucgate, trong khi trò chuyện với b|rep`,
      `nhấm nháp một tách cà phê phương Đông trong khi nói chuyện với b|rep`,
      `pha một thìa mật ong neko vào cà phê của b|rep, trong khi buôn chuyện`,
      `pha một ấm trà trong khi tán gẫu với b|rep`,
      `khuấy cặn trà trong khi nói chuyện với b|rep`,
      `kinh ngạc trước loại rượu lửa của người rồng mà b|rep mang đến, người đã nói`,
      `khoe cơ thể a|their của a|their với b|rep để chứng tỏ quan điểm của a|their`,
      `hỏi b|rep liệu b|they có thời gian để thảo luận không`,
      `thuyết phục được b|rep bằng kiến thức uyên bác của a|their về`,
    ],
  },
]

export const BANTER_VERB_SLAVER_RIVAL = [
  {
    verbs: [
      `dọa nạt b|rep về`,
      `đấm b|rep vì`,
      `tát b|rep vì`,
      `chơi khăm b|rep vì`,
      `xúc phạm b|rep về`,
      `xúc phạm b|rep về`,
      `coi thường b|rep về`,
      `phớt lờ b|rep vì`,
      `vu khống b|rep về`,
      `đá b|rep vì`,
      `đánh b|rep vì`,
      `đánh nhau với b|rep vì`,
      `không đồng ý với b|rep về`,
      `tranh luận với b|rep về`,
      `mâu thuẫn với b|rep về`,
      `xung đột với b|rep về`,
      `thách thức quyền lực của b|rep về`,
      `thách thức kỹ năng của b|rep về`,
      `thách thức ý kiến của b|rep về`,
      `coi thường quyền lực của b|rep về`,
      `coi thường kỹ năng của b|rep về`,
      `coi thường ý kiến của b|rep về`,
      `làm phiền b|rep về`,
      `cãi nhau với b|rep về`,
      `tranh cãi với b|rep về`,
      `gây gổ với b|rep về`,
      `đối đầu với b|rep về`,
      `chửi bới b|rep về`,
      `khiêu khích b|rep về`,
      `gây sự với b|rep về`,
      `chống đối b|rep về`,
      `bất tuân b|rep về`,
      `làm mất uy tín b|rep về`,
      `nói xấu b|rep về`,
      `làm bẽ mặt b|rep về`,
      `làm b|rep xấu hổ về`,
      `xa lánh b|rep vì`,
      `hắt hủi b|rep về`,
      `chê bai b|rep về`,
      `khinh miệt b|rep về`,
      `phỉ báng b|rep về`,
      `cằn nhằn với b|rep về`,
      `phàn nàn với b|rep về`,
      `phản đối với b|rep về`,
      `chỉ trích b|rep về`,
      `tố cáo b|rep về`,
      `lên án b|rep về`,
      `tấn công b|rep về`,
      `nói xấu b|rep về`,
      `chế giễu b|rep về`,
      `làm b|rep không vui về`,
      `làm b|rep khó chịu về`,
      `làm b|rep tức giận về`,
      `sống sót sau vài món ăn tự nấu của b|rep bằng cách trò chuyện về`,
      `từ chối cho b|rep bất kỳ miếng bơ cá voi phương Bắc nào vì bất đồng về`,
      `lấy trộm kẹo đá Hoang mạc của b|rep, trong khi giả vờ nói về`,
      `làm đổ cà ri orc nóng hổi lên b|rep trong một cuộc thảo luận nảy lửa về`,
      `ném một bát súp vào b|rep, sau một cuộc cãi vã về`,
      `say rượu sake và bắt đầu một cuộc ẩu đả với b|rep về`,
      `suýt nôn khi nghe ý kiến của b|rep về`,
      `thở dài sau khi thảo luận`,
      `bị làm phiền bởi ý kiến của b|rep về`,
      `làm phiền b|rep bằng cách mô tả quá chi tiết về`,
      `làm phiền b|rep bằng cách liên tục hỏi b|them về`,
      `nghi ngờ ý kiến của b|rep về`,
      `có một sự bất đồng với b|rep về`,
      `tát vào mông b|rep để đáp lại ý kiến của b|their về`,
      `mắng mỏ b|rep về`,
      `chơi khăm b|rep theo chủ đề`,
      `thầm lặng đánh giá suy nghĩ của b|rep về`,
    ],
  },
]


export const BANTER_VERB_SLAVER_LOVER = [
  {
    /* chung */
    verbs: [
      `hôn b|rep`,
      `vuốt ve b|rep`,
      `ôm b|rep`,
      `làm tình với b|rep`,
      `ngủ với b|rep`,
      `hôn hít b|rep`,
      `khen ngợi b|rep`,
      `trò chuyện nhỏ với b|rep`,
      `quan hệ tình dục với b|rep`,
      `trò chuyện nhỏ với b|rep`,

      `ôm b|rep`,
      `khiêu vũ với b|rep`,
      `thoát y cho b|rep`,
      `biểu diễn cho b|rep`,
      `ăn mặc gợi cảm cho b|rep`,
      `mời b|rep làm vài hiệp`,
      `quan hệ bất ngờ với b|rep`,
      `cùng nhau lên đỉnh với b|rep`,
      `nói chuyện tục tĩu với b|rep`,
      `chơi với núm vú của b|rep`,

      `tận hưởng cơ thể của b|rep`,
      `nghỉ ngơi cùng b|rep`,
      `phục vụ b|rep`,
      `cùng nhau hành hạ một nô lệ với b|rep`,
      `kích thích b|rep`,
      `nhìn vào mắt b|rep`,
      `ngắm nhìn khuôn mặt của b|rep`,
      `trao nhau những nụ hôn với b|rep`,
      `hôn lưỡi với b|rep`,
      `liếm cơ thể của b|rep`,

      `ngửi nách của b|rep`,
      `chạm vào cơ thể với b|rep`,
      `khóa môi với b|rep`,
      `chạm vào mặt b|rep`,
      `hát cho b|rep`,
      `ăn riêng với b|rep`,
      `mặc một bộ đồ gợi cảm cho b|rep`,
      `làm b|rep hứng tình`,
      `vuốt ve cơ thể của b|rep`,
      `lắc mông cho b|rep`,
    ],
  },
  {
    initiator: ["per_submissive"],
    verbs: [
      `phục tùng b|rep`,
      `dâng hiến cơ thể cho b|rep`,
      `dâng hiến bộ phận sinh dục cho b|rep`,
      `nhập vai nô lệ cho b|rep`,
      `nhập vai đồ chơi tình dục cho b|rep`,
      `thờ phụng b|rep`,
    ],
  },
  {
    target: ["muscle_strong"],
    verbs: [
      `chạm vào cơ bắp của b|rep`,
      `sờ soạng cơ bắp của b|rep`,
      `lần theo cơ bắp của b|rep`,
    ],
  },
  {
    target: ["muscle_thin"],
    verbs: [
      `chiêm ngưỡng b|body của b|rep`,
      `lần theo eo của b|rep`,
    ],
  },
  {
    target: ["per_submissive"],
    verbs: [
      `thống trị b|rep`,
      `vật hóa b|rep`,
      `đùa giỡn với b|body của b|rep`,
      `hành hạ b|rep`,
      `chơi trò chủ nhân-nô lệ với b|rep`,
    ],
  },
  {
    initiator: ["per_dominant"],
    target: ["per_submissive"],
    verbs: [
      `lạm dụng b|rep`,
    ],
  },
  {
    initiator: ["dick_tiny"],
    target: ["vagina_tight"],
    verbs: [
      `địt b|rep vào lồn`,
      `địt lồn b|rep`,
    ],
  },
  {
    target: ["vagina_tight"],
    verbs: [
      `liếm lồn b|rep`,
      `móc lồn b|rep`,
      `chơi với hột le của b|rep`,
    ],
  },
  {
    initiator: ["dick_tiny"],
    verbs: [
      `địt hậu môn b|rep`,
      `xuất tinh lên người b|rep`,
      `dâng dương vật cho b|rep`,
    ],
  },
  {
    initiator: ["vagina_tight"],
    verbs: [
      `ngồi lồn lên b|rep`,
      `dâng âm đạo cho b|rep`,
    ],
  },
  {
    target: ["dick_tiny"],
    verbs: [
      `thổi kèn cho b|rep`,
      `quay tay cho b|rep`,
      `sờ soạng b|dick của b|rep`,
      `làm b|rep$ lên đỉnh bất ngờ`,
    ],
  },
  {
    target: ["breast_tiny"],
    verbs: [
      `sờ soạng b|breasts của b|rep`,
      `chơi với b|breasts của b|rep`,
    ],
  },
  {
    initiator: ["breast_tiny"],
    target: ["breast_tiny"],
    verbs: [
      `cọ ngực với b|rep`,
    ],
  },
]


export const BANTER_VERB_SLAVE_CARE = [
  {
    verbs: [
      `chăm sóc b|rep`,
      `dỗ dành b|rep`,
      `nuôi dưỡng b|rep`,
      `chăm bẵm b|rep`,
      `kích thích b|rep`,
      `chữa trị cho b|rep`,
      `chăm sóc b|rep`,
      `trông nom b|rep`,
      `canh chừng b|rep`,
      `giúp đỡ b|rep`,
      `làm phong phú b|rep`,
      `giúp b|rep`,
      `tăng cường sức mạnh cho b|rep`,
      `giúp b|rep hồi phục`,
      `nói chuyện với b|rep`,
      `hỗ trợ nhiệm vụ nô lệ của b|rep`,
      `nhẹ nhàng sử dụng b|rep`,
      `nhẹ nhàng địt b|rep`,
      `nhẹ nhàng quan hệ tình dục với b|rep`,
      `chăm sóc b|rep`,
      `cổ vũ b|rep`,
      `bảo vệ b|rep`,
      `phục vụ b|rep`,
      `chia sẻ một câu chuyện với b|rep`,
      `để b|rep một mình`,
      `cho b|rep một ít thức ăn`,
      `cho b|rep ăn`,
      `chải chuốt cho b|rep`,
      `vuốt ve b|rep`,
      `ôm b|rep`,
      `vuốt ve b|rep`,
      `âu yếm b|rep`,
      `mân mê b|rep`,
      `vỗ về b|rep`,
      `nựng nịu b|rep`,
      `nuông chiều b|rep`,
      `thỏa mãn b|rep`,
      `ôm b|rep`,
      `trấn an b|rep`,
      `an ủi b|rep`,
      `khuyến khích b|rep`,
      `xoa dịu b|rep`,
      `làm dịu b|rep`,
      `dỗ dành b|rep`,
      `ru b|rep ngủ`,
      `dạy dỗ b|rep`,
      `làm tan biến nỗi sợ của b|rep`,
      `cho phép b|rep nghỉ ngơi`,
      `hát ru cho b|rep`,
      `cho b|rep nghỉ ngơi`,
    ],
  },
]


export const BANTER_VERB_SLAVE_ABUSE = [
  {
    /* chung */
    verbs: [
      `lạm dụng b|rep`,
      `trừng phạt b|rep`,
      `ngược đãi b|rep`,
      `địt b|rep`,
      `hành hạ b|rep`,
      `đối xử tệ bạc với b|rep`,
      `lạm dụng b|rep`,
      `quấy rối b|rep`,
      `đánh b|rep`,
      `đập b|rep`,
      `bắt nạt b|rep`,
      `tra tấn b|rep`,
      `đánh đập b|rep`,
      `làm nhục b|rep`,
      `phi nhân hóa b|rep`,
      `đá b|rep`,
      `hành hạ b|rep`,
      `sử dụng b|rep`,
      `xâm hại b|rep`,
      `tàn phá b|rep`,
      `làm hại b|rep`,
      `quấy rối b|rep`,
      `dày vò b|rep`,
      `bắt b|rep liếm nách a|their`,
      `bắt b|rep liếm a|genital của a|their`,
      `làm bẽ mặt b|rep`,
      `làm b|rep xấu hổ`,
      `kìm nén b|rep`,
      `quất roi b|rep`,
      `đánh roi b|rep`,
      `véo núm vú của b|rep`,
      `xoắn núm vú của b|rep`,
      `kéo núm vú của b|rep`,
      `hạ nhục b|rep`,
      `bắt b|rep liếm a|anus của a|their`,
      `bắt b|rep ăn a|ass của a|their`,
      `đánh đít b|rep`,
    ],
  },
  {
    initiator: ["dick_tiny"],
    verbs: [
      `địt vào mặt b|rep`,
      `bắn tinh lên mặt b|rep`,
      `địt hậu môn b|rep`,
      `bắt b|rep nghẹn vì a|dick của a|their`,
      `xuất tinh vào b|anus của b|rep`,
      `bắt b|rep bú a|dick của a|their`,
      `bắt b|rep bú sâu a|dick của a|their`,
      `vả bằng dương vật b|rep`,
      `bắt b|rep hôn a|dick của a|their`,
      `bắt b|rep liếm a|dick của a|their`,
    ],
  },
  {
    target: ["dick_tiny"],
    verbs: [
      `tra tấn b|dick của b|rep`,
      `giẫm lên b|dick của b|rep`,
      `bắt b|rep ăn tinh dịch của chính b|their`,
      `kìm nén b|rep`,
      `chơi với b|dick của b|rep`,
      `kẹp b|dick của b|rep`,
      `đánh vào b|dick của b|rep`,
      `gây sốc cho b|dick của b|rep`,
      `tát vào b|dick của b|rep`,
      `véo b|dick của b|rep`,
    ],
  },
  {
    target: ["breast_tiny"],
    verbs: [
      `tra tấn b|breasts của b|rep`,
      `giẫm lên b|breasts của b|rep`,
      `bắt b|rep uống sữa của chính b|their từ b|breasts của b|their`,
      `sờ soạng b|breasts của b|rep`,
      `chơi với b|breasts của b|rep`,
      `kẹp b|breasts của b|rep`,
      `đánh vào b|breasts của b|rep`,
      `gây sốc cho b|breasts của b|rep`,
      `tát vào b|breasts của b|rep`,
      `véo b|breasts của b|rep`,
    ],
  },
  {
    target: ["balls_tiny"],
    verbs: [
      `tra tấn b|balls của b|rep`,
      `giẫm lên b|balls của b|rep`,
      `bắt b|rep ăn tinh dịch của chính b|their`,
      `sờ soạng b|balls của b|rep`,
      `chơi với b|balls của b|rep`,
      `kẹp b|balls của b|rep`,
      `đánh vào b|balls của b|rep`,
      `gây sốc cho b|balls của b|rep`,
      `tát vào b|balls của b|rep`,
      `véo b|balls của b|rep`,
    ],
  },
  {
    target: ["vagina_tight"],
    initiator: ["dick_tiny"],
    verbs: [
      `địt lồn b|rep`,
      `bơm đầy b|vagina của b|rep bằng tinh dịch`,
      `chơi với b|vagina của b|rep`,
      `nhét dương vật giả vào b|vagina của b|rep`,
      `lạm dụng b|vagina của b|rep`,
    ],
  },
]

/* trường hợp đặc biệt: nô lệ không được huấn luyện */
export const BANTER_TRAINING_NONE = [
  `a|lời nào lời nấy đều tỏ ra thách thức`,
  `a|nhìn những kẻ bắt giữ mình một cách lệch lạc`,
  `a|khao khát tự do của a|their`,
  `a|giận dữ nhìn chủ nô của bạn`,
  `a|tiếp tục chế nhạo chủ nô của bạn`,

  `a|tiếp tục thách thức hầu hết các mệnh lệnh được giao cho a|them`,
  `vẫn a|tin a|they a|is là một người tự do`,
  `vẫn a|tin vào việc được giải cứu một ngày nào đó`,
  `a|is vẫn còn bám víu vào những khái niệm ngu ngốc như tự do`,
  `thách thức a|chửi thề bất cứ khi nào có cơ hội`,

  `a|cố gắng thách thức việc huấn luyện của a|their`,
  `a|vẫn chưa được thuần hóa`,
  `a|tiếp tục bám víu vào hy vọng`,
  `thách thức a|không tuân theo các mệnh lệnh được giao cho a|them`,
  `cố tình a|đi ngược lại các mệnh lệnh được giao của a|their`,

  `a|phá vỡ các quy tắc nô lệ của a|their`,
  `vẫn a|ghê tởm khái niệm nô lệ`,
  `say mê a|ghét công ty của bạn`,
  `a|tức giận vì hoàn cảnh của a|their`,
  `a|tiếp tục thề sẽ chấm dứt công ty của bạn`,
]

/* trường hợp đặc biệt: nô lệ bị hủy hoại tâm trí */
export const BANTER_TRAINING_MINDBREAK = [
  `a|có vẻ mặt trống rỗng`,
  `luôn a|mất tập trung`,
  `a|luôn trong trạng thái mơ màng`,
  `luôn a|giữ nguyên một biểu cảm`,
  `a|không phản ứng với các kích thích`,

  `a|chảy nước dãi liên tục`,
  `a|không thể xử lý bất kỳ thông tin nào`,
  `a|không hiểu tình hình của a|their`,
  `a|hoàn toàn bị hủy hoại tâm trí`,
  `a|đã hoàn toàn mất đi quá trình suy nghĩ cao cấp của a|their`,

  `a|chẳng khác gì một món đồ chơi tình dục rỗng tuếch`,
  `a|luôn nhìn xa xăm`,
  `a|duy trì một cái nhìn không tập trung`,
  `a|không thể xử lý bất kỳ mệnh lệnh nào`,
  `a|không thể hiểu bất cứ điều gì đang xảy ra xung quanh a|them`,

  `a|đã mất khả năng suy nghĩ của a|their`,
  `a|có con ngươi không bao giờ di chuyển`,
  `a|nhìn chủ nô của bạn với ánh mắt trống rỗng`,
  `a|không phản ứng với sự lạm dụng của chủ nô của bạn`,
  `a|không có ý chí tự do cũng như bị ép buộc`,
]

/* huấn luyện cơ bản, nâng cao, bậc thầy */
export const BANTER_TRAINING_VERB = [
  [
    `miễn cưỡng a|xin`, `khó chịu a|xin`, `a|bị bắt phải van xin`,
    `không muốn a|xin`, `a|bị buộc phải xin`,
  ],
  [
    `a|van xin`, `a|thèm khát`, `a|đã được huấn luyện để van xin`,
    `a|tìm kiếm`, `a|xin phép`,
  ],
  [
    `không thể không van xin`,
    `mãnh liệt a|thèm khát`,
    `theo bản năng a|tìm kiếm`,
    `a|sẵn sàng làm bất cứ điều gì để có được`,
    `liên tục a|hạ thấp a|themself với hy vọng có được`,
    `a|đã trải qua quá trình huấn luyện sâu rộng để luôn khao khát`,
  ],
]

/* văn bản huấn luyện */
export const BANTER_TRAINING_OBJECT = {
  training_obedience_basic: [
    `mệnh lệnh tiếp theo của a|their`,
    `chỉ thị tiếp theo của a|their`,
    `mệnh lệnh tiếp theo từ a|their`,
    `chỉ thị của chủ nhân a|their`,
    `sự cho phép từ chủ nhân a|their`,
    `mệnh lệnh từ chủ nhân a|their`,
    `mệnh lệnh của chủ nhân a|their`,
    `mệnh lệnh của chủ nhân a|their`,
    `mệnh lệnh của bạn`,
    `chỉ thị của bạn`,
  ],
  training_oral_basic: [
    `dương vật để bú`,
    `tinh dịch để nuốt`,
    `dương vật để bú sâu`,
    `dương vật để liếm`,
    `dương vật để thờ phụng bằng miệng của a|their`,
    `dương vật của chủ nhân a|their để nhét vào miệng a|their`,
    `dương vật của chủ nhân a|their để bắn tinh đầy miệng a|their`,
    `tinh dịch của chủ nhân a|their để liếm sạch trên sàn`,
    `một dương vật giả để bú trong khi chờ đợi phục vụ dương vật tiếp theo`,
    `bộ phận sinh dục của bạn`,
  ],
  training_anal_basic: [
    `dương vật để nhét vào mông a|their`,
    `dương vật để lấp đầy mông a|their bằng tinh dịch`,
    `những dương vật để lấp đầy mông a|their`,
    `những dương vật để thâm nhập vào cái mông thiếu thốn của a|their`,
    `dương vật để làm thỏa mãn bằng mông của a|their`,
    `dương vật của chủ nhân a|their để nhét vào mông a|their`,
    `dương vật của chủ nhân a|their để lấp đầy mông a|their bằng tinh dịch`,
    `nhiều dương vật để lấp đầy mông a|their`,
    `một dương vật giả để bịt mông trong khi chờ đợi phục vụ dương vật tiếp theo`,
    `bộ phận sinh dục của bạn`,
  ],
  training_vagina_basic: [
    `dương vật để nhét vào âm đạo a|their`,
    `dương vật để lấp đầy âm đạo a|their bằng tinh dịch`,
    `những dương vật để lấp đầy âm đạo a|their`,
    `những dương vật để thâm nhập vào cái âm đạo thiếu thốn của a|their`,
    `dương vật để làm thỏa mãn bằng âm đạo của a|their`,
    `dương vật của chủ nhân a|their để nhét vào âm đạo a|their`,
    `dương vật của chủ nhân a|their để lấp đầy âm đạo a|their bằng tinh dịch`,
    `nhiều dương vật để lấp đầy âm đạo a|their`,
    `một dương vật giả để bịt âm đạo trong khi chờ đợi phục vụ dương vật tiếp theo`,
    `bộ phận sinh dục của bạn`,
  ],
  training_sissy_basic: [
    `chủ nhân để làm thỏa mãn`,
    `chủ nhân để phục vụ`,
    `chủ nhân để khoe vẻ nữ tính của a|their`,
    `những dương vật để thờ phụng`,
    `những dương vật để phủ phục trước`,
    `bộ phận sinh dục của chủ nhân a|their để thờ phụng`,
    `cơ thể của chủ nhân a|their để thờ phụng`,
    `bộ phận sinh dục của bạn`,
    `cơ thể của bạn`,
  ],
  training_pet_basic: [
    `chủ nhân của a|their để chơi trò nhặt đồ`,
    `chủ nhân của a|their để ngửi`,
    `bàn chân của chủ nhân a|their để liếm sạch`,
    `bộ phận sinh dục của chủ nhân a|their để liếm`,
    `giày của chủ nhân a|their để liếm sạch`,
    `bát chó để ăn`,
    `những dương vật để ăn như một phần thưởng`,
    `chủ nhân của a|their cho một cuộc đi dạo`,
    `bàn chân của bạn để liếm`,
    `bạn để chơi trò nhặt đồ`,
  ],
  training_pony_basic: [
    `chủ nhân của a|their để được cưỡi`,
    `chủ nhân của a|their để ngửi`,
    `chủ nhân của a|their để sử dụng a|them như một con thú chở hàng mà a|they a|is`,
    `roi cưỡi của chủ nhân a|their để quất a|them`,
    `xe ngựa của chủ nhân a|their để kéo`,
    `máng để ăn`,
    `sự chú ý của chủ nhân a|their`,
    `sự chăm sóc của chủ nhân a|their`,
    `bạn và cây roi cưỡi của bạn`,
    `bạn để cưỡi a|them`,
  ],
  training_dominance_basic: [
    `một nô lệ phục tùng để thống trị`,
    `chủ nhân của a|their để hỏi về nô lệ tiếp theo để thống trị`,
    `nô lệ đồng bạn để thống trị`,
    `những người khác để thống trị`,
    `những người có tâm trí yếu hơn để thống trị`,
    `chủ nhân của a|their để xin phép thống trị người khác`,
    `những nô lệ khác để quất roi`,
    `những nô lệ khác để kỷ luật`,
    `những nô lệ khác để huấn luyện`,
    `bạn để xin phép sử dụng nô lệ của bạn`,
  ],
  training_masochist_basic: [
    `sự lạm dụng của chủ nhân a|their`,
    `bị lạm dụng`,
    `bị tra tấn bởi chủ nhân a|their`,
    `chủ nhân của a|their để trừng phạt họ`,
    `nhiều hình phạt hơn`,
    `nhiều đau đớn hơn`,
    `những hình phạt từ chủ nô của bạn`,
    `quất roi mạnh`,
    `sự lạm dụng của bạn`,
    `bạn để lạm dụng a|them`,
  ],
  training_toilet_basic: [
    `nước tiểu của chủ nhân a|their`,
    `bị sử dụng như một cái bồn cầu`,
    `bị sử dụng như một cái bồn tiểu`,
    `chất dịch cơ thể của chủ nhân a|their`,
    `bị lắp đặt trong nhà vệ sinh của bạn`,
    `bị đái lên người`,
    `nước tiểu của chủ nô của bạn`,
    `bị sử dụng như một cái bồn cầu sống`,
    `nước tiểu của bạn`,
    `bạn để sử dụng a|them như một cái bồn cầu`,
  ],
  training_endurance_basic: [
    `mệnh lệnh của chủ nhân a|their`,
    `bị sử dụng như một cái ghế`,
    `bị sử dụng như một cái ghế đẩu`,
    `bị sử dụng như một vật trang trí`,
    `chủ nhân của a|their để chơi với cơ thể a|their`,
    `chủ nhân của a|their để chơi với bộ phận sinh dục a|their`,
    `bị lắp đặt như một bức tượng`,
    `bị lắp đặt như một vật trang trí sống`,
    `bị sử dụng như ghế của bạn`,
    `bị quấy rối bởi bạn`,
  ],
  training_horny_basic: [
    `chỉ thị của chủ nhân a|their`,
    `mệnh lệnh của chủ nhân a|their`,
    `bị kìm nén`,
    `được phép xuất tinh`,
    `chủ nhân của a|their cho phép xuất tinh`,
    `chủ nhân của a|their cho phép cương cứng`,
    `bộ phận sinh dục của a|their bị hành hạ`,
    `sự cho phép để xuất tinh`,
    `sự cho phép của bạn để xuất tinh`,
    `mệnh lệnh tiếp theo của bạn`,
  ],
  training_roleplay_basic: [
    `những ảo tưởng để thực hiện`,
    `những vở kịch để diễn`,
    `những ham muốn đen tối nhất của chủ nhân a|their`,
    `những ham muốn bí mật của chủ nhân a|their`,
    `những ảo tưởng của chủ nhân a|their`,
    `gương để luyện tập lời nói`,
    `những ảo tưởng bí mật sâu thẳm nhất của bạn`,
  ],
  training_domestic_basic: [
    `những căn phòng để dọn dẹp`,
    `những phòng tắm để dọn dẹp`,
    `những sàn nhà để quét`,
    `chủ nhân của a|their để phục vụ`,
    `chủ nô của bạn để phục vụ`,
    `những căn phòng bẩn để lau sạch`,
    `những công việc lặt vặt để hoàn thành`,
    `chủ nhân của a|their để ra lệnh cho a|them`,
    `mệnh lệnh của bạn`,
    `những nơi bẩn nhất trong pháo đài của bạn để dọn dẹp`,
  ],
}
